{
 "cells": [
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Case Study:\n",
    "\n",
    "The following is a preview for a particular dataset.\n",
    "\n",
    "(For better viewing of the graphs make sure that images have a white background - night mode is off)\n",
    "\n",
    "([Here](#1-12) you can find some explantions for terms used in the following descriptions)\n",
    "\n",
    "### About the dataset:\n",
    "The dataset (found [here](https://catalog.data.gov/dataset/spirit-of-east-austin-feedback-data)) is from an efford by the Health Equity and Community Engagement department of the city of Austin Texas to identify the needs of the community, in the summer of 2017. The open-ended answers were isolated and used.\n",
    "\n",
    "#### Access & Use of data:\n",
    "'Public: This dataset is intended for public access and use.\n",
    "Appreciation for the Health Equity and Community Engagement department for sharing their data openly.\n",
    "\n",
    "### Context\n",
    "\n",
    "For better analysis using this tool, knowledge of the context analyzed is necessary. Two runs on the same dataset are demonstrated with different context:\n",
    "\n",
    "#### Run-1: Analyzing answers in general categories\n",
    "\n",
    "- Open-ended answers were classified from the organization into seven categories: 'Education', 'Jobs', 'Transportation', 'Safety', 'Health', 'Housing Culture' and 'Environment'. Thus, 7 clusters were chosen for this run, having the specific analysis in mind. \n",
    "- Using the topic_dictionary.xlsx, keywords from answers in each category were used in the topic_dictionary.xlsx, in order to cluster answers into these categories.\n",
    "- Features with zero-information were manually added in the 'stop_word_list.xlsx' first column (with the number 1 in the column next to them) in order to be ignored from the analysis\n",
    "\n",
    "\n",
    "#### Run-2: Digging deeper into the subject matter by increasing cluster number\n",
    "- Modifying only topic_dictionary to only synonyms, and increasing the number of clusters from 7 to 34, reveals more sub-categories hidden in the answers.\n",
    "\n",
    "\n",
    "### Feature analysis of answers:\n",
    "\n",
    "- Identify main features of the corpus\n",
    "\n",
    "A bar chart showing the most frequently used features per answer, and the answer count per feature enables the user to easily identify terms and topics in the corpus.\n",
    "\n",
    "![Pic Can't be displayed](features_count.png \"Features in corpus\")\n",
    "\n",
    "\n",
    "The graph shown is for Run-1 on the dataset described. The 7 categories appear as the top 7 features used by the responders (based on the topic_dictionary created).\n",
    "\n",
    "- Uncover Hidden Patterns\n",
    "\n",
    "What are the correlations between various features? A bar chart per feature is made, by isolating answers that include that feature, and identifying all the other features used in the answers.  \n",
    "![Alt text](top_10_feature_dependencies.png \"Feature dependencies\")\n",
    "\n",
    "**The first bar to each subplot refers to the number of answers that include only the chosen feature, and no other.\n",
    "\n",
    "The graph shown is for Run-1 on the dataset described. Focusing on feature \"jobs\", we see that 5% of answers that include this feature, also include the feature \"housing_culture\", around 3% of them includes feature \"education\" and less than 3% of these answers include other features. Very few answers include only the feature \"jobs\" and no other, as can be seen from the first bar that is less than 0.5 %.\n",
    "\n",
    "\n",
    "- Remove Noise and Zero-Information Features for Cleaner Data Analysis\n",
    "\n",
    "![Alt text](stop_word_list.png \"screenshot of stop_word_list.xlsx used in run-1\")\n",
    "\n",
    "By completing a word in stop_word_list.xls file (in the first column), and writing 1 next to it, it is removed from the analysis. this way one can remove zero-information features from the analysis.\n",
    "\n",
    "- Group and Replace Features for More Focused Analysis\n",
    "\n",
    "The topic_dictionary.xlsx determines what features have the same meaning. All words in a column are replaced with the word in the first row. \n",
    "![Alt text](topic_dict.png \"screenshot of the topic_dictionary.xlsx used in run-1\")\n",
    "\n",
    "For \"Run-1\", words in the first rows were chosen according to the performed classifications. Words to be grouped were chosen by skimming the text.\n",
    "\n",
    "### Clustering the answers\n",
    "\n",
    "- Cluster Similar Responses for a Clear Understanding of Feedback\n",
    "\n",
    "Based on the chosen features, clustering is performed (K-Means clustering is used). The user must choose a number of clusters. The 'correctness' of the clusters number is relevant to the context. Smaller number of clusters reveals more general topics, while larger numbers (run-2) can reveal more subcategories.\n",
    "\n",
    "- Viewing the Overall Distribution of Clusters and Answer Counts\n",
    "\n",
    "A car chart is prepared showing the distribution of answers to clusters.\n",
    "![Alt text](cluster_counts.png \"Answer counts per cluster\")\n",
    "\n",
    "Note: General guideline 1: when choosing a cluster number, it is advised that most answers are distributed among many clusters and not a single cluster. Depending on context this may not apply. \n",
    "\n",
    "\n",
    "- Uncover the Topics of Feedback by drilling down into Individual Clusters\n",
    "\n",
    "![Alt text](features_per_cluster.png \"features per cluster for run-1\")\n",
    "\n",
    "For each cluster, a subplot shows the top features (based on answer counts). This can reveal topics covered by answers in that cluster.\n",
    "\n",
    "\n",
    "- Run 2: Identify more subcategories\n",
    "\n",
    "Modifying some of the parameters can reveal more sub-categories: Removing the categories from the topic_dictionary (except synonyms), and increasing the number of clusters from 7 to 35, more subcategories are revealed:\n",
    "\n",
    "![Alt text](features_per_cl.png \"features per cluster for run-2\")\n",
    "\n",
    "i.e. From features in cluster 7, one can distinguish that some can't afford to pay the rent. \n",
    "\n",
    "Note: General guideline 2: choose a number such that:\n",
    "   - features that are in a cluster cover the same topic\n",
    "   - no two clusters have similar features that describe the same topic.\n",
    "   - Modify cluster number and dictionaries accordingly.\n",
    "\n",
    "Requirements:\n",
    "   - files:\n",
    "      - answers to be analyzed in an .xlsx file named 'raw_data.xlsx' of the following structure:\n",
    "            - question is on the first row\n",
    "            - answers for one open-ended question below the question\n",
    "            - one answer per row, all in the first column\n",
    "\n",
    "      - three .xlsx files:\n",
    "         (1) 'topic_dictionary.xlsx'\n",
    "               operation described above\n",
    "      \n",
    "         (2) 'stop_word_list.xlsx'\n",
    "               operation described above\n",
    "\n",
    "         (3) 'parameters.xlsx': a file that has the values for the necessary parameters for the program to run. These parameters are:\n",
    "            - PRINT_INFO : print details - usefull when tuning with dictionaries (True/False)             \n",
    "            - CLUSTER_NO : number of clusters (integer)             \n",
    "            - TOP_FEATURES : number of top features to keep (integer)\n",
    "            - REPORT : Produce clustering report file named 'clustering_report.xlsx' (True/False)\n",
    "            - SAVE_FEATURES : Saves identified features in features.xlsx (True/False)\n",
    "            - PREDICT : Option to predict the cluster of an input sentence by the user and it's score (True/False) - currently not working correctly\n",
    "            - N_GRAMS_MIN : Define minimum N-gram to consider as feature (int)\n",
    "            - N_GRAMS_MAX : Define maximum N-gram to consider as feature (int)\n",
    "            - PORTER_OR_LEMMATIZER : choose porter stemmer (1) or WordNetLemmatizer (2)\n",
    "            - SAVE_VIZ : save vizualizations in current folder (True/False)\n",
    "\n",
    "\n",
    "   - dependencies:\n",
    "      python 3, numpy, pandas, nltk, scikitlearn\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "<a name='1-12'></a>\n",
    "#### Terms used:\n",
    "\n",
    "'n-gram': 'a contiguous sequence of n items from a given sample of text' [source](https://en.wikipedia.org/wiki/N-gram). Can be 1-gram -> 1 word, 2-gram -> 2-word sequence, n-gram-> n-word sequence.\n",
    "\n",
    "'feature': referes to a term (can be an n-gram) used that is characteristics to a group of answers and is readable by a machine. This can some times be correct-spelling words, understandable by humans (if lemmatization is used), or not (if porter-stemmer is used)\n",
    "\n",
    "'lemmatization': \"the process of grouping together the inflected forms of a word so they can be analysed as a single item, identified by the word's lemma\" [source](https://en.wikipedia.org/wiki/Lemmatisation)\n",
    "\n",
    "'stemming': 'the process of reducing inflected (or sometimes derived) words to their word stem, base or root form—generally a written word form' [source](https://en.wikipedia.org/wiki/Stemming)\n",
    "\n",
    "'Porter-Stemmer': A stemming algorithm  written by Martin Porter in 1980, widely used.\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.6"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "81794d4967e6c3204c66dcd87b604927b115b27c00565d3d43f05ba2f3a2cb0d"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
